# Generated by Django 2.2.5 on 2020-10-09 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='link',
            new_name='URL',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='name',
        ),
    ]
