# Generated by Django 2.2.5 on 2020-10-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0005_auto_20201009_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
